language: go

go:
    - 1.10.1
    - tip
os:
    - linux
    - osx

env:

before_install:
    - go get github.com/mattn/goveralls

script: 
    - make build
    - $GOPATH/bin/goveralls -service=travis-ci
